Switch to MIT license
2DegreesInvesting/r2dii.data pull request #143
Opened 2020-09-10 10:36 UTC by jdhoffa

Before merging this PR, we will need approval from all contributors

2020-09-10 11:21 UTC, maurolepore commented
I approve the change to MIT license.

The other human authors are @jdhoffa and @2diiKlaus. Not sure how to get approval from the institutional author "2 Degrees Investing Initiative"; maybe you Klaus or Jakob can represent 2DII?



```
Authors@R: 
    c(person(given = "Mauro",
             family = "Lepore",
...
      person(given = "Jackson",
             family = "Hoffart",
...
      person(given = "Klaus",
             family = "Hagedorn",
...
      person(given = "2 Degrees Investing Initiative",
...
             email = "contact@2degrees-investing.org"))
```

2020-09-10 11:22 UTC, maurolepore requested changes

2020-09-10 11:22 UTC, maurolepore commented on LICENSE.md
> +MIT License
I see this file but DESCRIPTION still mentions the old license. `usethis::use_mit_license()` should do the trick.

2020-09-10 11:35 UTC, maurolepore commented on LICENSE.md
> +MIT License
Done.

2020-09-10 11:35 UTC, maurolepore approved these changes

2020-09-10 12:12 UTC, maurolepore commented
@2diiKlaus, If you support the change to MIT license, can you please write a comment here stating so, e.g. 

> I approve the change to MIT license.

Also, who can approve on behalf of 2DII? Is it you too?

2020-09-10 12:13 UTC, maurolepore commented
@jdhoffa, as the author of this PR I assume you support the change to MIT license; but to leave no doubts, can you please write a comment here stating so, e.g.

> I approve the change to MIT license.

2020-09-10 12:15 UTC, jdhoffa commented
I approve the change to MIT license.

2020-09-10 16:09 UTC, 2diiKlaus commented
I support changing the license of this package to MIT.

2020-09-11 11:53 UTC, maurolepore requested changes
Did you use the usethis helper? I think a file is missing with the MIT license: LICENSE.md.

2020-09-11 11:53 UTC, maurolepore commented on LICENSE
> +COPYRIGHT HOLDER: 2 Degrees Investing Initiative France
I had expected this to read "2 Degrees Investing Initiative" -- without "France". 
Can you confirm?

2020-09-11 13:48 UTC, jdhoffa commented on LICENSE
> +COPYRIGHT HOLDER: 2 Degrees Investing Initiative France
it should have France, it will be the French entity holding the license

2020-09-11 16:36 UTC, maurolepore commented
@jdhoffa, given our discussion on Slack, it seems 2DII's directors approved this change. I suggest we merge and try get this to CRAN.

2020-09-11 16:37 UTC, maurolepore approved these changes
LGTM

2020-09-11 17:21 UTC, merged