fix borderline in `nace_classification` and `isic_classification`
2DegreesInvesting/r2dii.data pull request #170
Opened 2020-10-12 14:54 UTC by jdhoffa

Closes #163

2020-10-12 16:02 UTC, maurolepore approved these changes
LGTM. It would be great to have the opinion of @georgeharris2deg

2020-10-12 16:02 UTC, maurolepore commented on data-raw/isic_classification.csv
> +710,4,not in scope,FALSE
@georgeharris2deg, is this what you expected?
The PR has more changes than the ones I highlight here, but this snippet should give you an idea of the _kind_ of change that @jdhoffa did. Please check.

2020-10-12 17:15 UTC, maurolepore commented
@jdhoffa, did you update the regression references?

2020-10-12 17:16 UTC, maurolepore requested changes
I see errors on CI. It looks like we need to update the regression refferences.

2020-10-13 07:34 UTC, georgeharris2deg commented on data-raw/isic_classification.csv
> +710,4,not in scope,FALSE
This looks good to me. Thanks!

2020-10-13 11:26 UTC, maurolepore commented
Looks like we re good to merge. @jdhoffa ?

2020-10-13 11:31 UTC, jdhoffa commented
Just fixing something that I messed up, will reopen in a moment

2020-10-13 11:34 UTC, jdhoffa commented
Ok @maurolepore should be good to go now

2020-10-13 12:35 UTC, maurolepore commented on data-raw/data_dictionary/nace_classification.csv
> +nace_classification,code,double,Formatted NACE code with periods removed
:+1:

2020-10-13 12:36 UTC, maurolepore approved these changes

2020-10-13 12:36 UTC, merged